apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front-service
  labels:
    app: web-front-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-front-service
  template:
    metadata:
      labels:
        app: web-front-service
    spec:
      containers:
        - name: web-front-service
          # ECR 이미지 주소로 수정
          image: 039612853048.dkr.ecr.ap-northeast-2.amazonaws.com/web-front-service:latest
          # EKS에서는 Always를 권장
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9005
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:80
            - name: EDGE_SERVICE_URL
              value: http://edge-service:80